version: "3.7"
services:
  web:
    image: dirgadm/go-clean-arch:1
    restart: always
    container_name: superindo_task_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json
    networks:
      - network-bridge

  mysql:
    image: mysql:5.7
    container_name: superindo_task_sql
    command: mysqld --user=root
    volumes:
      - ./catalog.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    networks:
      - network-bridge
networks:
  network-bridge:
    driver: bridge
    
